repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: '\.(pdb|gro|top|sdf)$'
  - id: debug-statements
- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.2
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/econchick/interrogate
  rev: 1.7.0
  hooks:
    - id: interrogate
      args: ["openff/interchange/", "-e", "openff/interchange/_tests/"]
      pass_filenames: false
- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.18.0
  hooks:
  - id: blacken-docs
    files: ^docs/
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.41.0
  hooks:
  - id: markdownlint
    exclude: .github
    args: ["--disable", "MD013", "MD033", "MD024", "MD046", "--ignore", "docs/using/experimental.md", "--ignore", "docs/using/status.md", "--"]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.8.7
  hooks:
    - id: nbqa-pyupgrade
      files: ^examples
      args:
        - --py310-plus
    - id: nbqa-ruff
      files: ^examples
      args:
        - --fix
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
    - id: nbstripout
      files: ^examples
- repo: https://github.com/asottile/pyupgrade
  rev: v3.17.0
  hooks:
  - id: pyupgrade
    args:
      - --py310-plus
