version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-latest"
  jobs:
    pre_build:
      - mamba list

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

conda:
  environment: devtools/conda-envs/docs_env.yaml
