[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = true
ignore-semiprivate = false
ignore-private = true
ignore-property-decorators = false
ignore-module = false
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = true
ignore-regex = ["^Test.*", "test_.*", "^_.*"]
fail-under = 90

[tool.ruff]
line-length = 119

[tool.ruff.lint]
ignore = ["E721","D105","D107","D200","D203","D212"]
select = ["E", "F", "W", "NPY", "UP", "RUF"]

[tool.ruff.lint.per-file-ignores]
"openff/interchange/**/__init__.py" = ["F401"]
"openff/interchange/smirnoff/_nonbonded.py" = ["F821"]
"openff/interchange/*_pydantic.py" = ["F401"]
"openff/interchange/smirnoff/_gbsa.py" = ["F821"]
"openff/interchange/smirnoff/_virtual_sites.py" = ["F821"]
"openff/interchange/components/foyer.py" = ["F401"]
"plugins/*" = ["INP001"]
"openff/interchange/components/interchange.py" = ["F821"]
"openff/interchange/components/*.py" = ["F821"]
"openff/interchange/_tests/unit_tests/test_types.py" = ["F821"]
"openff/interchange/foyer/_nonbonded.py" = ["F821"]
"openff/interchange/_tests/data/*" = ["INP001"]
"versioneer.py" = ["UP", "RUF"]
"openff/interchange/_tests/*" = ["RUF015"]
"openff/interchange/smirnoff/_*.py" = ["RUF015"]

[tool.ruff.lint.pydocstyle]
property-decorators=["validator"]
